### ISSUE TITLE
mapreduce allocates a lot on the CPU

### ISSUE THREAD

**Issue by ViralBShah** [JuliaGPU/Metal.jl#211] opened 2023-06-22 12:19 UTC
I was expecting fewer allocations, and much faster speed for `sum(Vector)`, but I am not sure what to compare it to. 

```
## GPU

julia> a = Metal.ones(Float32, 10^8);

julia> @time sum(a)
  0.017176 seconds (980 allocations: 23.758 KiB)
1.0f8

## CPU

julia> b = ones(Float32,10^8);

julia> @time sum(b);
  0.014090 seconds (1 allocation: 16 bytes)
```

**Comment by tgymnich** [comment] 2023-06-22 12:31
These might help:
https://developer.apple.com/documentation/metalperformanceshaders/mpsmatrixsum
https://developer.apple.com/documentation/metalperformanceshaders/mpsnnreducerowsum
https://developer.apple.com/documentation/metalperformanceshaders/mpsnnreducecolumnsum

**Comment by maleadt** [comment] 2023-06-22 13:41
Yeah, `mapreduce` is known to be slow, https://github.com/JuliaGPU/Metal.jl/issues/46. We had sped it up at some point, but had to revert (https://github.com/JuliaGPU/GPUArrays.jl/pull/454), and I haven't had the time to revisit.

Adding specializations that use MPS might be a good workaround for the common cases.

**Comment by maleadt** [comment] 2024-03-05 13:55
Regarding the performance of mapreduce: I think we're fine, see https://github.com/JuliaGPU/Metal.jl/pull/303#issue-2168968353 for a benchmark

---

Regarding the allocations: I think we can close this in favor of https://github.com/JuliaInterop/ObjectiveC.jl/issues/13

Basically, these aren't caused by the `mapreduce` implementation, but are a consequence of how the ObjectiveC object wrappers are designed (all objects being abstract types resulting in dynamic dispatch everywhere).
For example, with the simplest kernel possible:

```julia
julia> f() = @metal identity(nothing)
f (generic function with 2 methods)

julia> @time f()
  0.000177 seconds (55 allocations: 1.578 KiB)
Metal.HostKernel{typeof(identity), Tuple{Nothing}}(identity, Metal.MTL.MTLComputePipelineStateInstance (object of type AGXG15XFamilyComputePipeline))
```

Because of these allocations almost all coming from object instances, they are generally small and thus very fast. As such, I don't think this is a performance issue/priority right now.

**Closed by maleadt** 2024-03-05 13:55 UTC
Labels: performance, arrays
