### ISSUE TITLE
`sysctlbyname` not found during pre-compilation

### ISSUE THREAD

**Issue by lukem12345** [JuliaGPU/Metal.jl#456] opened 2024-10-11 16:40 UTC
I'm adding support for Metal.jl in the CI/ CD for the CombinatorialSpaces.jl package, and am getting errors at pre-compile time when [adding Metal.jl as an extension](https://github.com/AlgebraicJulia/CombinatorialSpaces.jl/commit/453f5d5b3492f16587e5f86d632089a3da47204e).

I notice that there was a PR [98](https://github.com/JuliaGPU/Metal.jl/pull/98) that added support for this use case that works on some systems, but this errors here due to `sysctlbyname` not being found. Here is a [link](https://github.com/AlgebraicJulia/CombinatorialSpaces.jl/actions/runs/11244767087/job/31263485209) to the full error log of a Linux action that failed. (The accompanying MacOS action failed due to me misusing `Metal.functional()`.)

Right now, I [work around](https://github.com/AlgebraicJulia/CombinatorialSpaces.jl/blob/90bc20d1f6561f02ebfd5f7abbbccd0ab4b585fb/test/Backends.jl#L201) this by checking if `Sys.isapple()` before manually `Pkg.add`ing Metal.jl in the test suite.

**Comment by christiangnrd** [comment] 2024-10-12 02:12
This is a duplicate of #453 and is fixed in main by #454.

@maleadt This is the second report in 2 days. I think we should either:

1. Release v1.4.1 with #454 cherry-picked. I created a branch `release-1.4` if that's the option we choose.
2. Release v1.5.0. That seems soon, but maybe that doesn't matter?
3. Not rush a release, rename and pin this issue until the next release so people know how to work around it.

**Comment by maleadt** [comment] 2024-10-12 07:05
Thanks, I tagged the backport.

**Closed** 2024-10-12 07:05 UTC
